# Generated by Django 6.0.1 on 2026-02-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_lecture_reference_url_lecture_video_file_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitystudent',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='universitystudent',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='universitystudent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='universitystudent',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AddField(
            model_name='universitystudent',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الجنسية'),
        ),
        migrations.AddField(
            model_name='universitystudent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AddField(
            model_name='universitystudent',
            name='semester',
            field=models.PositiveIntegerField(blank=True, help_text='من 1 إلى 10', null=True, verbose_name='الفصل الدراسي'),
        ),
        migrations.AlterField(
            model_name='universitystudent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_students', to='academic.department', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='universitystudent',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='السنة الدراسية'),
        ),
    ]
