# Generated by Django 6.0.1 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_universitystudent_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_manager', 'System Manager'), ('department_manager', 'Department Manager'), ('supervisor', 'Supervisor'), ('teacher', 'Teacher'), ('ta', 'Teaching Assistant'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
