# Generated by Django 6.0.1 on 2026-02-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_lecture_reference_url_lecture_video_file_and_more'),
        ('accounts', '0004_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='academic.department', verbose_name='القسم'),
        ),
    ]
