# Generated by Django 6.0.1 on 2026-06-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_activitylog_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_manager', 'System Manager'), ('department_manager', 'Department Manager'), ('supervisor', 'Supervisor'), ('teacher', 'Teacher'), ('ta', 'Teaching Assistant'), ('student', 'Student'), ('event_manager', 'Event Manager')], default='student', max_length=20),
        ),
    ]
