# Generated by Django 6.0.1 on 2026-01-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالعربية')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('assignment_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=10, verbose_name='النوع')),
                ('due_date', models.DateTimeField(verbose_name='تاريخ التسليم')),
                ('max_grade', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='الدرجة القصوى')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='ملف مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رمز المادة')),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('academic_year', models.PositiveIntegerField(verbose_name='السنة الدراسية')),
                ('semester', models.PositiveIntegerField(default=1, verbose_name='الفصل الدراسي')),
                ('credit_hours', models.PositiveIntegerField(default=3, verbose_name='الساعات المعتمدة')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('teacher', 'Teacher'), ('ta', 'Teaching Assistant')], max_length=10, verbose_name='الدور')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Instructor',
                'verbose_name_plural': 'Course Instructors',
            },
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الدرجة الكلية')),
                ('letter_grade', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('F', 'F')], max_length=2, verbose_name='التقدير')),
                ('passed', models.BooleanField(verbose_name='ناجح')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشور')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Result',
                'verbose_name_plural': 'Course Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Department Name')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم القسم')),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالعربية')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('lecture_type', models.CharField(choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=10, verbose_name='النوع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('file', models.FileField(blank=True, null=True, upload_to='lectures/', verbose_name='ملف مرفق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lecture',
                'verbose_name_plural': 'Lectures',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='المحتوى')),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='الملف المرفق')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('feedback', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
