# Generated by Django 6.0.1 on 2026-01-29 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='department',
            name='department_manager',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'department_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL, verbose_name='مدير القسم'),
        ),
    ]
