# Generated by Django 6.0.1 on 2026-01-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_rename_supervisor_to_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='reference_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط المراجع'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/', verbose_name='ملف فيديو'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط يوتيوب أو فيميو', null=True, verbose_name='رابط فيديو خارجي'),
        ),
    ]
