# Generated by Django 6.0.1 on 2026-03-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_department_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='video_file',
        ),
        migrations.AddField(
            model_name='lecture',
            name='bunny_video_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='معرّف فيديو Bunny Stream'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='bunny_video_url',
            field=models.URLField(blank=True, help_text='رابط iframe للمشغّل المضمّن من Bunny Stream', null=True, verbose_name='رابط مشغّل فيديو Bunny'),
        ),
    ]
