# Generated by Django 6.0.1 on 2026-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_bunny_video_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='bunny_video_id',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='bunny_video_url',
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/videos/', verbose_name='ملف فيديو (MP4)'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lectures/files/', verbose_name='ملف مرفق'),
        ),
    ]
