# Generated by Django 6.0.1 on 2026-04-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_remove_lecture_bunny_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='المحتوى'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_type',
            field=models.CharField(blank=True, choices=[('theory', 'Theory'), ('lab', 'Lab')], max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='العنوان'),
        ),
    ]
