# Generated by Django 6.0.1 on 2026-06-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_alter_lecture_content_alter_lecture_lecture_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academic.lecture', verbose_name='المحاضرة المرتبطة'),
        ),
    ]
